name: util.html workflow

on: [push]
  push:
    tags:
    - /^v\d+\.\d+\.\d+(-[\.\w]+)?/

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@master
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        version: ${{ matrix.node-version }}
    - run: npm all
    - run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
